# Generated by Django 5.1.1 on 2024-10-07 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('open', 'Open-ended'), ('choice', 'Multiple choice')], default='choice', max_length=10),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(limit_choices_to={'question_type': 'choice'}, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
        migrations.CreateModel(
            name='OpenAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('question', models.ForeignKey(limit_choices_to={'question_type': 'open'}, on_delete=django.db.models.deletion.CASCADE, to='main.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Открытый ответ',
                'verbose_name_plural': 'Открытые ответы',
            },
        ),
    ]
