# Generated by Django 5.1.1 on 2024-10-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_question_type_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finaltest',
            name='course',
        ),
        migrations.RemoveField(
            model_name='finaltest',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='finaltestresult',
            name='final_test',
        ),
        migrations.RemoveField(
            model_name='finaltestresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='openanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='openanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='article',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='FinalTest',
        ),
        migrations.DeleteModel(
            name='FinalTestResult',
        ),
        migrations.DeleteModel(
            name='OpenAnswer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
