# Generated by Django 5.1.1 on 2024-10-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finaltest",
            name="questions",
        ),
    ]
