# Generated by Django 5.1.1 on 2024-10-10 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_question_test_remove_test_article_and_more"),
        ("tests", "0002_enrollment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="article",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="main.article",
            ),
        ),
    ]
