# Generated by Django 5.1.1 on 2024-10-11 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_question_correct_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Запись на тест', 'verbose_name_plural': 'Записи на тесты'},
        ),
        migrations.AddField(
            model_name='test',
            name='prerequisite_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tests.test'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('open', 'Открытый вопрос'), ('choice', 'Множественный выбор')], default='choice', max_length=10),
        ),
    ]
