# Generated by Django 5.1.1 on 2024-10-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0004_remove_finaltestresult_user_finaltestresult_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finaltestresult",
            name="total_questions",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="finaltestresult",
            name="score",
            field=models.IntegerField(),
        ),
    ]
