# Generated by Django 5.1.1 on 2024-10-15 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_enrollment_options_test_prerequisite_test_and_more'),
        ('users', '0002_enrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='tests',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='correct_answer',
            new_name='text_description',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='text_task',
        ),
        migrations.RemoveField(
            model_name='test',
            name='prerequisite_test',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='attempt_count',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='user',
        ),
        migrations.AddField(
            model_name='testresult',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='total_questions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('text', 'Text')], max_length=17),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(),
        ),
    ]
