# Generated by Django 5.1.1 on 2024-10-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_enrollment_options_and_more'),
        ('users', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
